ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 7
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id003 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 81388800000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1630454400000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          O99PbS/XNkE=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          ZmZmZmybAEE=
    - - Arrival Rooms
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Compliment Rooms
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - House Use
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Individual Confirm
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Arr
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - Departure Rooms
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - is_weekend
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - month
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - quarter
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - is_holiday
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - rolling_mean_7d
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - rolling_std_7d
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - rolling_mean_14d
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - rolling_std_14d
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id003
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                O99PbS/XNkE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ZmZmZmybAEE=
          - - Arrival Rooms
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Compliment Rooms
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - House Use
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Individual Confirm
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Arr
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - Departure Rooms
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - is_weekend
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - month
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - quarter
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - is_holiday
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - rolling_mean_7d
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - rolling_std_7d
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - rolling_mean_14d
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - rolling_std_14d
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object/apply:collections.OrderedDict
- - - Arrival Rooms
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - Compliment Rooms
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - House Use
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - Individual Confirm
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - Arr
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - Departure Rooms
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - is_weekend
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - month
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - quarter
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - is_holiday
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - rolling_mean_7d
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - rolling_std_7d
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - rolling_mean_14d
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
  - - rolling_std_14d
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: true
      reg_lambda: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 365.25
        resolution: 6
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 7
        resolution: 3
  reg_lambda: 0
  weekly_arg: true
  yearly_arg: true
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 120
  lambda_delay: 60
  learning_rate: 0.01
  loss_func: !!python/object:neuralprophet.custom_loss_metrics.PinballLoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - - - loss_func
        - !!python/object:torch.nn.modules.loss.SmoothL1Loss
          _backward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _buffers: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
          - []
          _is_full_backward_hook: null
          _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _modules: !!python/object/apply:collections.OrderedDict
          - []
          _non_persistent_buffers_set: !!set {}
          _parameters: !!python/object/apply:collections.OrderedDict
          - []
          _state_dict_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          beta: 0.3
          reduction: none
          training: true
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    quantiles: &id004
    - 0.5
    - 0.025
    - 0.975
    reduction: mean
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 936
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles: *id004
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 15
  trend_global_local: global
  trend_reg: 0
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: []
max_lags: 7
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 1
n_lags: 7
num_seasonalities_modelled: 1
num_trends_modelled: 1
